In [1]:
import keras
import tensorflow as tf


config = tf.ConfigProto( device_count = {'GPU': 1 , 'CPU': 10} ) 
sess = tf.Session(config=config) 
keras.backend.set_session(sess)

Using TensorFlow backend.


In [2]:
print("Tensor Flow Version: {}".format(tf.__version__))

Tensor Flow Version: 1.13.1


In [5]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

In [6]:
# !pip install requests

In [7]:
df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression

# Build the neural network
model = Sequential()
model.add(Dense(25, #Number of neurons in the first layer
                input_dim=x.shape[1], # Number of columns in the dataset (or size of picture, this parameter takes all the dimensions but the dimension that corresponds to the number of samples)
                activation='relu')) # Hidden 1
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # One neuron because we are dealing with regression problem
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
 - 1s - loss: 597369.7458
Epoch 2/100
 - 0s - loss: 42331.4554
Epoch 3/100
 - 0s - loss: 8345.2515
Epoch 4/100
 - 0s - loss: 6770.5373
Epoch 5/100
 - 0s - loss: 323.3547
Epoch 6/100
 - 0s - loss: 556.7790
Epoch 7/100
 - 0s - loss: 107.3566
Epoch 8/100
 - 0s - loss: 109.6168
Epoch 9/100
 - 0s - loss: 78.9051
Epoch 10/100
 - 0s - loss: 78.8592
Epoch 11/100
 - 0s - loss: 76.1935
Epoch 12/100
 - 0s - loss: 76.7220
Epoch 13/100
 - 0s - loss: 76.2721
Epoch 14/100
 - 0s - loss: 76.6083
Epoch 15/100
 - 0s - loss: 75.9515
Epoch 16/100
 - 0s - loss: 76.1172
Epoch 17/100
 - 0s - loss: 76.7687
Epoch 18/100
 - 0s - loss: 75.9118
Epoch 19/100
 - 0s - loss: 75.9420
Epoch 20/100
 - 0s - loss: 75.6152
Epoch 21/100
 - 0s - loss: 75.4861
Epoch 22/100
 - 0s - loss: 75.1874
Epoch 23/100
 - 0s - loss: 75.7379
Epoch 24/100
 - 0s - loss: 74.8318
Epoch 25/100
 - 0s - loss: 74.8621

In [8]:
#Make predictions
pred = model.predict(x)
print("Shape: {}".format(pred.shape))
print(pred)

Shape: (398, 1)
[[12.482341 ]
 [15.832072 ]
 [15.729106 ]
 [17.892956 ]
 [15.757701 ]
 [15.2847395]
 [17.22462  ]
 [17.973217 ]
 [18.678234 ]
 [17.033886 ]
 [10.410533 ]
 [15.9375105]
 [ 4.3167524]
 [-3.8693132]
 [31.822826 ]
 [18.500652 ]
 [18.567242 ]
 [14.239604 ]
 [31.341015 ]
 [18.020336 ]
 [31.27287  ]
 [31.52592  ]
 [32.835217 ]
 [34.501324 ]
 [16.1067   ]
 [31.989574 ]
 [35.24708  ]
 [36.262524 ]
 [35.447765 ]
 [31.564007 ]
 [25.25288  ]
 [31.380932 ]
 [31.565365 ]
 [13.742106 ]
 [20.128185 ]
 [14.223918 ]
 [10.910991 ]
 [16.907757 ]
 [18.658398 ]
 [14.606029 ]
 [14.934215 ]
 [19.184399 ]
 [21.172619 ]
 [14.689647 ]
 [18.027294 ]
 [13.849925 ]
 [20.976635 ]
 [14.019267 ]
 [10.148875 ]
 [26.97044  ]
 [28.767986 ]
 [28.780468 ]
 [29.232769 ]
 [27.510998 ]
 [27.66183  ]
 [22.049587 ]
 [25.900463 ]
 [31.752483 ]
 [28.849194 ]
 [22.511272 ]
 [25.926281 ]
 [27.04533  ]
 [19.213757 ]
 [14.389537 ]
 [19.571362 ]
 [15.065074 ]
 [19.597118 ]
 [19.798412 ]
 [17.626781 ]
 [18.714245 ]
 [18

In [9]:
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Final score (RMSE): {score}")

Final score (RMSE): 7.727367163327036


## Classification

In [10]:
df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Classification
species = dummies.columns
y = dummies.values

In [12]:
species

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')

In [13]:
# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
 - 0s - loss: 1.0870
Epoch 2/100
 - 0s - loss: 0.9923
Epoch 3/100
 - 0s - loss: 0.9218
Epoch 4/100
 - 0s - loss: 0.8771
Epoch 5/100
 - 0s - loss: 0.8440
Epoch 6/100
 - 0s - loss: 0.8090
Epoch 7/100
 - 0s - loss: 0.7750
Epoch 8/100
 - 0s - loss: 0.7412
Epoch 9/100
 - 0s - loss: 0.7100
Epoch 10/100
 - 0s - loss: 0.6778
Epoch 11/100
 - 0s - loss: 0.6483
Epoch 12/100
 - 0s - loss: 0.6171
Epoch 13/100
 - 0s - loss: 0.5844
Epoch 14/100
 - 0s - loss: 0.5554
Epoch 15/100
 - 0s - loss: 0.5282
Epoch 16/100
 - 0s - loss: 0.5034
Epoch 17/100
 - 0s - loss: 0.4786
Epoch 18/100
 - 0s - loss: 0.4480
Epoch 19/100
 - 0s - loss: 0.4211
Epoch 20/100
 - 0s - loss: 0.3991
Epoch 21/100
 - 0s - loss: 0.3775
Epoch 22/100
 - 0s - loss: 0.3613
Epoch 23/100
 - 0s - loss: 0.3453
Epoch 24/100
 - 0s - loss: 0.3315
Epoch 25/100
 - 0s - loss: 0.3188
Epoch 26/100
 - 0s - loss: 0.3063
Epoch 27/100
 - 0s - loss: 0.2950
Epoch 28/100
 - 0s - loss: 0.2865
Epoch 29/100
 - 0s - loss: 0.2815
Epoch 30/100
 - 0s - lo

In [14]:
# Prediction
pred = model.predict(x)
print("Shape: {pred.shape}")
print(pred)

Shape: {pred.shape}
[[9.98974681e-01 1.02525530e-03 9.08500297e-08]
 [9.96189415e-01 3.81000433e-03 6.38434187e-07]
 [9.98228490e-01 1.77120336e-03 3.06117045e-07]
 [9.95563507e-01 4.43549128e-03 1.09553218e-06]
 [9.99145627e-01 8.54240498e-04 8.04126685e-08]
 [9.98863459e-01 1.13639503e-03 7.51284546e-08]
 [9.98223007e-01 1.77662424e-03 3.55281912e-07]
 [9.98146415e-01 1.85338885e-03 2.17234899e-07]
 [9.94361758e-01 5.63633069e-03 1.94435870e-06]
 [9.96403933e-01 3.59548046e-03 5.52726760e-07]
 [9.99219775e-01 7.80165603e-04 4.34621086e-08]
 [9.97216702e-01 2.78280722e-03 4.58235377e-07]
 [9.96566296e-01 3.43311764e-03 5.99749796e-07]
 [9.98389244e-01 1.61032367e-03 4.31749299e-07]
 [9.99854565e-01 1.45371028e-04 3.06884829e-09]
 [9.99826252e-01 1.73824694e-04 4.65175098e-09]
 [9.99682426e-01 3.17646278e-04 1.55085313e-08]
 [9.98867869e-01 1.13198371e-03 1.08840091e-07]
 [9.98809218e-01 1.19076588e-03 5.29059179e-08]
 [9.99210119e-01 7.89720973e-04 6.60740156e-08]
 [9.96780276e-01 3.2

In [15]:
# Usually the column (pred) with the highest prediction is considered to be the prediction of the neural network.  It is easy
# to convert the predictions to the expected iris species.  The argmax function finds the index of the maximum prediction
# for each row.
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
[species[i] for i in predict_classes]

['Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',


In [18]:
from sklearn.metrics import accuracy_score
# Accuracy might be a more easily understood error metric.  It is essentially a test score.  For all of the iris predictions,
# what percent were correct?  The downside is it does not consider how confident the neural network was in each prediction.
correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.9866666666666667


## Part 3.3: Saving and Loading a Keras Neural Network
Complex neural networks will take a long time to fit/train. It is helpful to be able to save these neural networks so that they can be reloaded later. A reloaded neural network will not require retraining. Keras provides three formats for neural network saving.

YAML - Stores the neural network structure (no weights) in the YAML file format.
JSON - Stores the neural network structure (no weights) in the JSON file format.
HDF5 - Stores the complete neural network (with weights) in the HDF5 file format. Do not confuse HDF5 with HDFS. They are different. We do not use HDFS in this class.
Usually you will want to save in HDF5.

In [19]:
save_path = "."
# Save neural network structure to JSON (no weights)
model_json = model.to_json()
with open(os.path.join(save_path,"network.json"), "w") as json_file:
    json_file.write(model_json)

# Save neural network structure to YAML (no weights)
model_yaml = model.to_yaml()
with open(os.path.join(save_path,"network.yaml"), "w") as yaml_file:
    yaml_file.write(model_yaml)

# Save entire network to HDF5 (save everything, suggested)
model.save(os.path.join(save_path,"network.h5"))

In [20]:
from keras.models import load_model
model2 = load_model(os.path.join(save_path,"network.h5"))
pred = model2.predict(x)
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"After load score (RMSE): {score}")

After load score (RMSE): 0.11395354568958282


In [21]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3